### PR TITLE
Fix for Feature Issue #100: Storage Module s3: add options to set boto3 read_timeout and retries

### PR DESCRIPTION
**Pull request by wech71**
Added option to increate boto3 retries. 

Please review - I'm not a regular python developer, but it did work on my system ;-)

### CODE REVIEW

**Comment by elemental-lf** [comment]
Thanks for the contribution! I'll take a look soon.

**Comment by elemental-lf** [comment]
@wech71 did you actually need to adjust the read timeout for your use case? I'm asking because there is also a connect timeout and I think it would be more consistent to either add both options or none of them.

Regarding the retry configuration it might be useful to switch from `legacy` to `standard` mode which according to the documentation is a better alternative. See https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html. That is in addition to adding the `max_attempts` option.

**Comment by wech71** [comment]
@elemental-lf no, not in particular. I was not able to reproduce the problem for testing, so I just guessed this would be the correct setting. I totally agree that it would make more sense to add both options!

An improved retry mode also sounds like a good idea. I must confess that I did not read the documentation at all, but just the code, so this did'd see this

**Comment by elemental-lf** [comment]
@wech71 I've just opened #103 which includes an improved version of this PR.

**Pull request closed without merging**
