### PR TITLE
support backup rbd images in any rados namespace, make k8s-tools to better support CSI

### PR DESCRIPTION
**Pull request by jpsn123**
for now benji just can backup rbd without namespace, but my rbd images are distributed in different namespaces.
benji `backup rbd:pool_name/namespace_name/image_name@snap1` database cant work. 

Improved k8s-tools backup logic to better support CSI, now freezing image works properly before snapshots.

### CODE REVIEW

**Comment by bjw-s** [comment]
It would be awesome if this could be merged. My rook-ceph instance isn't installed in the default `rook-ceph` namespace, and the current script therefore does not work for me.

**Comment by dren-dk** [comment]
I'm also waiting for a release containing this fix, has the benji project been abandoned?

**Comment by elemental-lf** [comment]
Thank you for your contribution and sorry for the delay in reviewing your PR. I will try to integrate your changes in the next few days.

**Comment by elemental-lf** [comment]
@jpsn123 I've rewritten and adapted your changes and most of them are now included in the `master` branch.  Thanks again for your contribution.

**Pull request closed without merging**
